paths:
  uploads: uploads
  uploads_use_relative_path: true
  static: ''
  dam_uploads: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  data:
    path: _data
    output: false
    filter:
      base: all
      include:
      exclude:
        - nav.yml
    description: ''
    icon: notes
    _editables:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
  pages:
    path: ''
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  layout:
    type: auto
    hidden: true
    cascade: true
  hero_position:
    type: auto
    hidden: true
    cascade: true
  summary_description:
    type: auto
    label: Summary
    comment: This description will show up on the home page.
    cascade: true
  class_description:
    type: auto
    comment: This description will show up on the class page.
    cascade: true
  bio:
    type: textarea
    cascade: true
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
data_config: {}
timezone: Etc/UTC
